services:
  # Servicio de la aplicación Laravel (PHP + Apache)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    # Mapeamos el puerto 80 del contenedor al 80 de la máquina local
    ports:
      - "80:80"
      - "5173:5173"
    # Vinculamos la carpeta local con la carpeta /var/www/html del contenedor
    volumes:
      - ./:/var/www/html
    # Variables de entorno (por ejemplo, para Composer o npm si es necesario)
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db

  # Servicio de base de datos MySQL 8
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root_secret
    ports:
      - "3306:3306"
    volumes:
      # Para persistir los datos de la base de datos
      - dbdata:/var/lib/mysql

# Declaramos un volumen para guardar datos de MySQL
volumes:
  dbdata: